### ISSUE TITLE
Snake doesn't get game over when it collides itself 

### ISSUE THREAD

**Issue by rhinojosadev** [mitjapotocin/snake-game#5]
Hi @mitjapotocin 
I think there is a little issue with the current logic
![SnakeCollision](https://user-images.githubusercontent.com/3522527/95024609-b987dc00-0649-11eb-84d4-5beb2ad93a9e.png)

I think in this scenario should mark game over right?
If this is true, can I work on this?

Thanks!

**Comment by mitjapotocin** [comment]
@rene-ph, thanks for the issue report, sorry didn't see your issue in time. There are sure more bugs to be found.
